// @generated by @ilha/router — do not edit

declare module "ilha:pages/server" {
  import type { RouterBuilder } from "@ilha/router";
  import type { Island } from "ilha";
  export const pageRouter: RouterBuilder;
  export const registry: Record<string, Island<any, any>>;
}

declare module "ilha:pages/client" {
  import type { RouterBuilder } from "@ilha/router";
  import type { Island } from "ilha";
  export const pageRouter: RouterBuilder;
  export const registry: Record<string, Island<any, any>>;
}

declare module "ilha:loaders" {
  // Side-effect-only module. Importing it attaches loaders to pageRouter.
}
