// @generated by @ilha/router — do not edit
// Server module. Use for SSR and SSG/prerender.
// Import via: import { pageRouter, registry } from "ilha:pages/server";

import { router, wrapLayout, wrapError } from "@ilha/router";
import type { Island } from "ilha";
import { default as _page0 } from "../src/pages/index.tsx";

const _wrapped0 = _page0;

export const registry: Record<string, Island<any, any>> = {
  index: _wrapped0,
};

export const pageRouter = router().route("/", _wrapped0);
